
server:
  servlet:
    context-path: /exo
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    url: jdbc:postgresql://127.0.0.1:5432/exo
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        show_sql: true
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
